// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/geometry.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        float32                `protobuf:"fixed32,1,opt,name=height,proto3" json:"height,omitempty"`
	Width         float32                `protobuf:"fixed32,2,opt,name=width,proto3" json:"width,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RectRequest) Reset() {
	*x = RectRequest{}
	mi := &file_proto_geometry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RectRequest) ProtoMessage() {}

func (x *RectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geometry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RectRequest.ProtoReflect.Descriptor instead.
func (*RectRequest) Descriptor() ([]byte, []int) {
	return file_proto_geometry_proto_rawDescGZIP(), []int{0}
}

func (x *RectRequest) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *RectRequest) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

type AreaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float32                `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AreaResponse) Reset() {
	*x = AreaResponse{}
	mi := &file_proto_geometry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AreaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaResponse) ProtoMessage() {}

func (x *AreaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geometry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaResponse.ProtoReflect.Descriptor instead.
func (*AreaResponse) Descriptor() ([]byte, []int) {
	return file_proto_geometry_proto_rawDescGZIP(), []int{1}
}

func (x *AreaResponse) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type PermiterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float32                `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermiterResponse) Reset() {
	*x = PermiterResponse{}
	mi := &file_proto_geometry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermiterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermiterResponse) ProtoMessage() {}

func (x *PermiterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geometry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermiterResponse.ProtoReflect.Descriptor instead.
func (*PermiterResponse) Descriptor() ([]byte, []int) {
	return file_proto_geometry_proto_rawDescGZIP(), []int{2}
}

func (x *PermiterResponse) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_proto_geometry_proto protoreflect.FileDescriptor

const file_proto_geometry_proto_rawDesc = "" +
	"\n" +
	"\x14proto/geometry.proto\x12\x02pb\";\n" +
	"\vRectRequest\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x02R\x06height\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x02R\x05width\"&\n" +
	"\fAreaResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x02R\x06result\"*\n" +
	"\x10PermiterResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x02R\x06result2p\n" +
	"\x0fGeometryService\x12)\n" +
	"\x04Area\x12\x0f.pb.RectRequest\x1a\x10.pb.AreaResponse\x122\n" +
	"\tPerimeter\x12\x0f.pb.RectRequest\x1a\x14.pb.PermiterResponseB\fZ\n" +
	"pkg/api/pbb\x06proto3"

var (
	file_proto_geometry_proto_rawDescOnce sync.Once
	file_proto_geometry_proto_rawDescData []byte
)

func file_proto_geometry_proto_rawDescGZIP() []byte {
	file_proto_geometry_proto_rawDescOnce.Do(func() {
		file_proto_geometry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_geometry_proto_rawDesc), len(file_proto_geometry_proto_rawDesc)))
	})
	return file_proto_geometry_proto_rawDescData
}

var file_proto_geometry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_geometry_proto_goTypes = []any{
	(*RectRequest)(nil),      // 0: pb.RectRequest
	(*AreaResponse)(nil),     // 1: pb.AreaResponse
	(*PermiterResponse)(nil), // 2: pb.PermiterResponse
}
var file_proto_geometry_proto_depIdxs = []int32{
	0, // 0: pb.GeometryService.Area:input_type -> pb.RectRequest
	0, // 1: pb.GeometryService.Perimeter:input_type -> pb.RectRequest
	1, // 2: pb.GeometryService.Area:output_type -> pb.AreaResponse
	2, // 3: pb.GeometryService.Perimeter:output_type -> pb.PermiterResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_geometry_proto_init() }
func file_proto_geometry_proto_init() {
	if File_proto_geometry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_geometry_proto_rawDesc), len(file_proto_geometry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_geometry_proto_goTypes,
		DependencyIndexes: file_proto_geometry_proto_depIdxs,
		MessageInfos:      file_proto_geometry_proto_msgTypes,
	}.Build()
	File_proto_geometry_proto = out.File
	file_proto_geometry_proto_goTypes = nil
	file_proto_geometry_proto_depIdxs = nil
}
